version: '3'
services:
  influxdb:
      build: influxdb
      ports:
          - "8086:8086"
      volumes:
          - ./influx_data:/var/lib/influxdb
      env_file:
          - 'env.influxdb'
  grafana:
      image: grafana/grafana:latest
      ports:
          - "3000:3000"
      volumes:
          - ./grafana_data:/var/lib/grafana